stages:
  - deploy  

pages:
  stage: deploy  # Set this new job to run in the `deploy` stage
  script:
    - mkdir public
    - cp -r src/* public/
  artifacts:
    paths:
      - "public/"
  only:
    - main
